SELECT USER
FROM DUAL;

-- 실습 테이블 생성(TBL_MEMBERLIST)
CREATE TABLE TBL_MEMBERLIST
( MID   NUMBER,
  NAME  VARCHAR2(30),
  TEL   VARCHAR2(50),
  CONSTRAINT MEMBERlIST_MID_PK PRIMARY KEY(MID)
);

-- 시퀀스 생성(MEMBERLISTSEQ)
CREATE SEQUENCE MEMBERLISTSEQ
NOCACHE;

-- 샘플 데이터 입력
INSERT INTO TBL_MEMBERLIST(MID,NAME,TEL)
VALUES(MEMBERLISTSEQ.NEXTVAL, '정도전','010-1234-5678');

-- 입력된 내용 확인
SELECT MID,NAME,TEL
FROM TBL_MEMBERLIST;

-- 커밋
COMMIT;



